### ISSUE TITLE
Solucionar bugs

### ISSUE THREAD

**Issue by saritagrimal2** [Arquisoft/Agents_e1b#4]
A través del index.html de site se han encontrado los siguientes bugs:

![captura](https://user-images.githubusercontent.com/32536740/35941548-e6b20e4c-0c52-11e8-9187-9e0d6211736b.JPG)

![captura2](https://user-images.githubusercontent.com/32536740/35941556-f022d39e-0c52-11e8-88f4-b1982a1d0eeb.JPG)

**Comment by sankosk** [comment]
Se me olvidó cerrarlo, por la tarde hice un mvn site y al desaparecer el atributo edad ya no había ningún bug relacionado
